FROM python:3.11.12-slim as builder

WORKDIR /app

RUN addgroup --system pygroup && adduser --system --ingroup pygroup pyuser

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

ENV PORT=8000

FROM python:3.11.12-slim as Final

COPY ./app /app/app

RUN chown -R pyuser:pygroup /app

USER pyuser

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]