apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: falcon-api-binding
  namespace: falcon
subjects:
  - kind: ServiceAccount
    name: falcon-api-sa
    namespace: falcon
roleRef:
  kind: Role
  name: falcon-api-Role
  apiGroup: rbac.authorization.k8s.io
